### ISSUE TITLE
get segment from TimeItem

### ISSUE THREAD

**Issue by ghn** [sethdeckard/m3u8#12]
Hello,
I've tried parsing my file

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:1582061
#EXTINF:10, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-01-01T18:22:09Z
20160321T150304_2_5560256_1582061.ts
#EXTINF:10, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-01-01T18:22:19Z
20160321T150304_2_5560256_1582062.ts
```

I get a list of TimeItem which makes sens, but how can I get the filename (.ts) ? Does this lib support this format?
thanks

**Comment by sethdeckard** [comment]
Hi, thanks for reporting this. It doesn't currently support this but it needs to. I'll dig into it as soon as I get a chance to.

**Comment by ghn** [comment]
Hi,
I'm considering fixing this right now, however I don't know much about this format atm. What do you think is best?
- add 'segment' to 'TimeItem' or
- add 'timestamp' to SegmentItem'

**Comment by ghn** [comment]
done in #16

**Comment by sethdeckard** [comment]
Thanks again!
