### ISSUE TITLE
Support for Name attribute in #EXT-X-STREAM-INF

### ISSUE THREAD

**Issue by raphi** [sethdeckard/m3u8#13]
Hi,

would you consider a PR that would add the non-standard `Name` attribute to `#EXT-X-STREAM-INF`?

This is used by Wowza and JWPlayer to show a quality selector option in the player (see https://support.jwplayer.com/customer/portal/articles/1430240-hls-adaptive-streaming )

Thanks

**Comment by sethdeckard** [comment]
Definitely, it looks like a good option to support. Thank you.
