### ISSUE TITLE
create mp4 file from playlist

### ISSUE THREAD

**Issue by jcohenho** [sethdeckard/m3u8#18]
Is it possible to create an mp4 file from a given playlist url?

**Comment by sethdeckard** [comment]
Not with this gem alone, you would also need something like FFmpeg. You can use this library to parse each media playlist and get the URI of each MPEG-2 transport stream file that makes up each segment of the playlist. You'd then use FFmpeg to concatenate all the individual transport stream files from a single media playlist and remux it into a MP4 (assuming you want to preserve codecs).

**Comment by jcohenho** [comment]
Thanks, I was able to use FFmpeg to create an mp4 directly from a m3u8 playlist URL.
