### ISSUE TITLE
#EXT-X-ENDLIST needs to be set when the stream finishes

### ISSUE THREAD

**Issue by fruwe** [sethdeckard/m3u8#22]
If a live stream finishes, the #EXT-X-ENDLIST tag must be included in the end

See [6.2.1.  General Server Responsibilities](https://tools.ietf.org/html/draft-pantos-http-live-streaming-22#section-6.2.1)

>    If the Media Playlist contains the final Media Segment of the
>    presentation then the Playlist file MUST contain the EXT-X-ENDLIST
>    tag; this allows clients to minimize unproductive Playlist reloads.

**Comment by sethdeckard** [comment]
Hi @fruwe, can you please explain what the library is doing wrong in this case?

**Comment by fruwe** [comment]
Hi @sethdeckard,

Thanks for responding so quickly.
My deepest apologies, it seems that I have not seen the the new `live` option. My mistake.

Anyway, great gem, thanks a lot

I close this issue

**Comment by sethdeckard** [comment]
No problem and you're welcome.
